### ISSUE TITLE
FordPass Widget Errors

### ISSUE THREAD

**Issue by aksten** [tonesto7/ford-pwr-up-info#11]
Can you please fix the fordpass widget?
There are a lot of people who really love that widget and can no longer use it. 
I relied on this heavily and now I have to use the Siri shortcuts which are no where near as convenient.

**Comment by aksten** [comment]
You’re not even gonna respond? 
If you have no intention of fixing the app at least have the decency to respond to the many many issues being opened on there asking for help letting them know the project is dead.

**Comment by tonesto7** [comment]
I’m not sure who you're talking to and why you feel so entitled to ask a question about a different piece of software in here!   
I can’t fix the fucking widget yet.  Do a bit of research and maybe you will find out why!
