### ISSUE TITLE
Missing 23-PU0105-DC-CHG2 for Mach E

### ISSUE THREAD

**Issue by rsjaffe** [tonesto7/ford-pwr-up-info#13]
**Improved DC Fast Charging**

We know how important DC Fast Charging is to you, so we've tweaked the charging module to improve reliability and performance.

Ford Power-Up software updates like this let us make improvements without the inconvenience of asking you to leave home. At Ford, we value your continued satisfaction and we respect your time.
Priority Update 23-PU0105-DC-CHG2

**Comment by tonesto7** [comment]
thanks for this... It was added a while ago
