### ISSUE TITLE
Question: Ford Power Up Release Notes

### ISSUE THREAD

**Issue by Delamater** [tonesto7/ford-pwr-up-info#15]
Question: 
Thank you for your Ford Power Up github page, it is very useful for tracking updates that should be coming down the pipe for my F-150. Simple question, do you know why Ford does provide more details on what the update actually does? These update notices are extremely sparse on details. Do you happen to know if we should be going somewhere else to get the real details on what these updates really do? 

Here's a couple examples to demonstrate my meaning: 
 - update 22-PU1009-DOR-CM/TLC-CSM, "Quality improvement to your trailer position/license plate lights." What exactly is this? I feel like it should be explained somewhere a bit more. 
 - 4.2.4, "Added In-Vehicle Voice Feedback to share instant feedback with Ford". Where do we go to actually give this feedback?

Thanks again for your great contribution. This website was very helpful to me to know I was behind on updates as I was stuck in OTA purgatory there for a while.

**Comment by tonesto7** [comment]
I agree 100%, but we only share the descriptions that ford shares with these updates :(
