### ISSUE TITLE
Add update: 23-PU0724-DOM-RS

### ISSUE THREAD

**Issue by mszczewski** [tonesto7/ford-pwr-up-info#17]
Ford pushed an additional update I don’t see in the log. 23-PU0724-DOM-RS

Text of the update in the Ford Pass App:
Digital Owner's Manual
We made sure that what you need to know is in there and easy to find. Go see it on Ford.com/support or in the FordPass® App.
You can also access it in your vehicle through the
SYNC®4 touchscreen under the Features tab or through the SYNC® 4A touchscreen under Apps.
Ford Power-Up delivers software updates that are designed to help make your Ford F-150® truck better over time.

![IMG_2928](https://github.com/tonesto7/ford-pwr-up-info/assets/24794669/8e5e83d0-4d0b-4fc0-a783-09be099cd3ad)

**Comment by marcelosinhorini** [comment]
can't find this in the log, closed by mistake? or should I raise a PR? tnks
